#!/bin/bash
# DRYAD.AI Enhanced Installation - Configuration Generators
# Functions for generating configuration files

# Source utilities if not already sourced
if [[ -z "$DRYAD_UTILS_LOADED" ]]; then
    source "$(dirname "${BASH_SOURCE[0]}")/utils.sh"
fi

# Generate backend .env file
generate_backend_env() {
    print_step "Generating backend configuration..."
    
    # Generate secure JWT secret
    local jwt_secret=$(generate_secret)
    
    # Create .env file
    cat > .env << EOF
# DRYAD Backend Configuration
# Generated by install_dryad_enhanced.sh on $(date)

# Deployment
DEPLOYMENT_CONFIG=$DEPLOYMENT_CONFIG
ENVIRONMENT=production

# API Configuration
API_HOST=0.0.0.0
API_PORT=8000
API_BASE_URL=http://${DOMAIN}:8000
API_TITLE=DRYAD.AI Backend API
API_VERSION=1.0.0

# Database
$(if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " postgresql " ]]; then
  echo "DATABASE_URL=postgresql://dryad:dryad@localhost:5432/dryad"
else
  echo "DATABASE_URL=sqlite:///./dryad.db"
fi)

# LLM Provider
LLM_PROVIDER=$LLM_PROVIDER
$(if [[ "$LLM_PROVIDER" == "openai" && -n "$OPENAI_API_KEY" ]]; then
  echo "OPENAI_API_KEY=$OPENAI_API_KEY"
fi)
$(if [[ "$LLM_PROVIDER" == "anthropic" && -n "$ANTHROPIC_API_KEY" ]]; then
  echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
fi)
$(if [[ "$LLM_PROVIDER" == "ollama" ]]; then
  echo "OLLAMA_BASE_URL=http://localhost:11434"
  echo "OLLAMA_MODEL=llama3.2:3b"
fi)

# Vector Database
WEAVIATE_URL=http://localhost:8080
WEAVIATE_API_KEY=

# Redis
REDIS_URL=redis://localhost:6379
REDIS_DB=0

# Security
JWT_SECRET_KEY=$jwt_secret
JWT_ALGORITHM=HS256
JWT_EXPIRATION=3600
SECRET_KEY=$jwt_secret

# MCP Server
$(if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " mcp " ]]; then
  echo "ENABLE_MCP_SERVER=true"
  echo "MCP_ENDPOINT_PATH=/mcp"
  echo "MCP_SERVER_HOST=0.0.0.0"
  echo "MCP_SERVER_PORT=8000"
fi)

# Monitoring
$(if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " monitoring " ]]; then
  echo "ENABLE_METRICS=true"
  echo "PROMETHEUS_ENABLED=true"
  echo "METRICS_PORT=9090"
fi)

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
$(if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " logging " ]]; then
  echo "ENABLE_ELK=true"
  echo "ELASTICSEARCH_URL=http://localhost:9200"
fi)

# CORS
CORS_ORIGINS=["http://localhost:3000","http://localhost:3001","http://localhost:3006","http://${DOMAIN}:3000","http://${DOMAIN}:3001","http://${DOMAIN}:3006"]

# Celery (if enabled)
$(if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " celery " || "$DEPLOYMENT_CONFIG" == "full" || "$DEPLOYMENT_CONFIG" == "scalable" ]]; then
  echo "CELERY_BROKER_URL=redis://localhost:6379/1"
  echo "CELERY_RESULT_BACKEND=redis://localhost:6379/2"
fi)

# Feature Flags
ENABLE_WEBSOCKET=true
ENABLE_GRAPHQL=true
ENABLE_SWAGGER=true

EOF

    print_success "Backend .env file created"
}

# Check for port conflicts
check_port_conflicts() {
    print_step "Checking for port conflicts..."
    
    local ports_to_check=(
        "8000:DRYAD Backend"
        "8080:Weaviate"
        "6379:Redis"
    )
    
    # Add LLM provider ports
    if [[ "$LLM_PROVIDER" == "ollama" ]]; then
        ports_to_check+=("11434:Ollama")
    fi
    
    # Add frontend ports
    if [[ " ${SELECTED_FRONTENDS[@]} " =~ " dryads-console " ]]; then
        ports_to_check+=("3001:Dryads Console")
    fi
    if [[ " ${SELECTED_FRONTENDS[@]} " =~ " university-ui " ]]; then
        ports_to_check+=("3006:University UI")
    fi
    if [[ " ${SELECTED_FRONTENDS[@]} " =~ " writer-portal " ]]; then
        ports_to_check+=("3000:Writer Portal")
    fi
    
    # Add monitoring ports
    if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " monitoring " ]]; then
        ports_to_check+=("9090:Prometheus" "3000:Grafana")
    fi
    
    # Add logging ports
    if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " logging " ]]; then
        ports_to_check+=("9200:Elasticsearch" "5601:Kibana")
    fi
    
    # Add PostgreSQL port
    if [[ " ${OPTIONAL_COMPONENTS[@]} " =~ " postgresql " ]]; then
        ports_to_check+=("5432:PostgreSQL")
    fi
    
    local conflicts=()
    
    for port_info in "${ports_to_check[@]}"; do
        local port="${port_info%%:*}"
        local service="${port_info##*:}"
        
        if is_port_in_use "$port"; then
            conflicts+=("Port $port ($service) is already in use")
        fi
    done
    
    if [[ ${#conflicts[@]} -gt 0 ]]; then
        print_warning "Port conflicts detected:"
        for conflict in "${conflicts[@]}"; do
            echo "  - $conflict"
        done
        echo ""
        
        if ! confirm "Do you want to continue anyway?" "n"; then
            print_error "Installation cancelled due to port conflicts"
            exit 1
        fi
    else
        print_success "No port conflicts detected"
    fi
}

