# ============================================================================
# DRYAD.AI Backend - Prometheus Alert Rules
# Critical, warning, and info level alerts
# ============================================================================

groups:
  # ==========================================================================
  # Application Health Alerts
  # ==========================================================================
  - name: application_health
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up{job="DRYAD.AI-backend"} == 0
        for: 1m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "DRYAD.AI Backend service is down"
          description: "Backend instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: WorkerDown
        expr: up{job="DRYAD.AI-worker"} == 0
        for: 2m
        labels:
          severity: warning
          component: worker
        annotations:
          summary: "Self-healing worker is down"
          description: "Worker instance {{ $labels.instance }} has been down for more than 2 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

  # ==========================================================================
  # Performance Alerts
  # ==========================================================================
  - name: performance
    interval: 30s
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.instance }}."

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 10m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 / 1024 > 3
        for: 10m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}GB on {{ $labels.instance }}."

  # ==========================================================================
  # Self-Healing System Alerts
  # ==========================================================================
  - name: self_healing
    interval: 30s
    rules:
      - alert: SelfHealingTaskFailed
        expr: increase(self_healing_tasks_failed_total[10m]) > 3
        for: 5m
        labels:
          severity: critical
          component: self-healing
        annotations:
          summary: "Multiple self-healing tasks failed"
          description: "{{ $value }} self-healing tasks have failed in the last 10 minutes."

      - alert: SelfHealingTaskPending
        expr: self_healing_tasks_pending > 10
        for: 30m
        labels:
          severity: warning
          component: self-healing
        annotations:
          summary: "Many pending self-healing tasks"
          description: "{{ $value }} self-healing tasks are pending approval."

      - alert: GuardianNotRunning
        expr: guardian_running == 0
        for: 5m
        labels:
          severity: critical
          component: guardian
        annotations:
          summary: "Guardian agent is not running"
          description: "Guardian agent has stopped on {{ $labels.instance }}."

  # ==========================================================================
  # Database Alerts
  # ==========================================================================
  - name: database
    interval: 30s
    rules:
      - alert: DatabaseConnectionPoolExhausted
        expr: db_connection_pool_size - db_connection_pool_available < 2
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Only {{ $value }} connections available in the pool."

      - alert: SlowDatabaseQueries
        expr: rate(db_query_duration_seconds_sum[5m]) / rate(db_query_duration_seconds_count[5m]) > 1
        for: 10m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is {{ $value }}s."

  # ==========================================================================
  # LLM/AI Alerts
  # ==========================================================================
  - name: llm_ai
    interval: 30s
    rules:
      - alert: LLMHighLatency
        expr: histogram_quantile(0.95, rate(llm_request_duration_seconds_bucket[5m])) > 10
        for: 5m
        labels:
          severity: warning
          component: llm
        annotations:
          summary: "LLM requests are slow"
          description: "95th percentile LLM latency is {{ $value }}s."

      - alert: LLMHighErrorRate
        expr: rate(llm_requests_failed_total[5m]) / rate(llm_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: llm
        annotations:
          summary: "High LLM error rate"
          description: "LLM error rate is {{ $value | humanizePercentage }}."

      - alert: MultiAgentSystemStalled
        expr: multi_agent_tasks_running > 0 and rate(multi_agent_tasks_completed_total[10m]) == 0
        for: 15m
        labels:
          severity: warning
          component: multi-agent
        annotations:
          summary: "Multi-agent system appears stalled"
          description: "No tasks completed in 10 minutes despite {{ $value }} running tasks."

  # ==========================================================================
  # Infrastructure Alerts
  # ==========================================================================
  - name: infrastructure
    interval: 30s
    rules:
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

      - alert: DiskSpaceCritical
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.05
        for: 1m
        labels:
          severity: critical
          component: infrastructure
        annotations:
          summary: "Critical disk space"
          description: "Disk space is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

      - alert: ContainerRestarting
        expr: rate(container_restart_count[15m]) > 0
        for: 5m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Container is restarting"
          description: "Container {{ $labels.name }} is restarting frequently."

  # ==========================================================================
  # Security Alerts
  # ==========================================================================
  - name: security
    interval: 30s
    rules:
      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "Rate limit exceeded frequently"
          description: "Rate limit exceeded {{ $value }} times per second."

      - alert: AuthenticationFailures
        expr: rate(authentication_failures_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High authentication failure rate"
          description: "{{ $value }} authentication failures per second."

      - alert: SuspiciousActivity
        expr: rate(suspicious_requests_total[5m]) > 1
        for: 2m
        labels:
          severity: critical
          component: security
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} suspicious requests per second detected."

